{{ if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "extopy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "extopy.labels" . | indent 4 }}
  {{- with .Values.secretAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  mysql-username: {{ .Values.mysql.auth.username | default "root" | b64enc | quote }}
  {{ if not .Values.mysql.auth.existingSecret }}
  mysql-password: {{ .Values.mysql.auth.rootPassword | b64enc | quote }}
  {{ end }}
{{ end }}
